import { docsConfig } from "@timmo001/docs-kit/blume";
import { defineConfig } from "blume";
import commandPages from "./commands-sidebar.json" with { type: "json" };

export default defineConfig(
  docsConfig({
    title: "Home Assistant Bridge",
    description:
      "One shared Home Assistant connection for your machine, served to local apps over a single socket.",
    site: "ha-bridge.timmo.dev",
    github: { owner: "timmo001", repo: "ha-bridge" },
    navigation: {
      sidebar: [
        "/",
        "/install",
        "/configuration",
        "/running",
        {
          label: "Actions",
          root: "/actions",
          items: [
            "/actions/lights",
            "/actions/switches",
            "/actions/input-booleans",
            "/actions/input-numbers",
            "/actions/covers",
            "/actions/climate",
            "/actions/assist-satellites",
            "/actions/cameras",
            "/actions/buttons",
            "/actions/locks",
            "/actions/valves",
            "/actions/sirens",
            "/actions/remotes",
            "/actions/selects",
            "/actions/values",
            "/actions/counters",
            "/actions/scripts",
            "/actions/automations",
            "/actions/scenes",
            "/actions/timers",
            "/actions/groups",
            "/actions/fans",
            "/actions/humidifiers",
            "/actions/media-players",
            "/actions/vacuums",
            "/actions/alarms",
            "/actions/updates",
            "/actions/notifications",
            "/actions/todo-lists",
            "/actions/calendars",
            "/actions/conversation",
            "/actions/images",
            "/actions/alerts",
            "/actions/system",
            "/actions/supervisor",
            "/actions/commands",
            "/actions/home-assistant",
          ],
        },
        {
          label: "Using",
          items: [
            "/using/reading",
            "/using/search",
            "/using/templates",
            "/using/events",
            "/using/history",
            "/using/bar-json",
            "/using/completions",
            "/using/protocol",
          ],
        },
        "/libraries",
        {
          label: "Commands",
          root: "/commands",
          items: commandPages.filter((page) => page !== "/commands"),
          display: "group",
          collapsed: true,
        },
        {
          label: "Migrations",
          items: ["/from-go-automate"],
        },
      ],
    },
    redirects: [
      { from: "/migrating", to: "/from-go-automate" },
      { from: "/using/actions", to: "/actions" },
      { from: "/using/watching", to: "/using/reading" },
      { from: "/reference/bar-json", to: "/using/bar-json" },
      { from: "/reference/protocol", to: "/using/protocol" },
      { from: "/reference/commands/:slug*", to: "/commands/:slug*" },
    ],
    theme: {
      accent: {
        light: "#0277bd",
        dark: "#03a9f4",
      },
    },
  }),
);
